# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10 # basically tells Circle to use Node.js docker runner to deploy the app to Now on every push
    working_directory: ~/repo
    steps: # A list of steps to be performed
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: sudo yarn global add now --no-save  # Install Now CLI on GitLab CI
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run deploy !! :)
      - run: now -p -t $NOW_TOKEN
    branches:
      ignore:
        - master